### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by docwhomc** [OpenVoxelStandards/OpenVoxelStandards#1]
Add a license to the Open Voxel Standards (OVS) repository.

**Comment by docwhomc** [comment]
As indicated by the name (shared by the org and repo), it should be an license.

**Comment by docwhomc** [comment]
A stipulation that modified versions, derived works, proposals, etc. identify themselves as such would seem warranted.  After all, a standard isn't really much of a standard if their are multiple, conflicting versions of it that can't be differentiated from one another.

**Comment by docwhomc** [comment]
I'm leaning towards using the [GNU Free Documentation License (FDL) Version 1.3](https://www.gnu.org/licenses/fdl-1.3.en.html) for the standards themselves and the [GNU General Public License (GPL) Version 3](https://www.gnu.org/licenses/gpl-3.0.en.html) for reference implementations of the standards (with the standard &ldquo;or any later version&rdquo; option).

**Comment by Geolykt** [comment]
Using the GPL would be counterintuitive unless it is meant to be only applied by open source projects using the GPL. (I'm not so sure if a project using MIT/X11/BSD/etc.  would be able to use the GPL'd reference implementations - if anything I'd use the LGPL)

**Comment by docwhomc** [comment]
Those are GPL compatible licenses, so software licensed under then can be used in a project that uses GPL software, so long as that project is available under the GPL.

**Comment by docwhomc** [comment]
Resolved by commit https://github.com/OpenVoxelStandards/OpenVoxelStandards/commit/a9ae34642c87baadca5acac5085c9e580b141884.  The project will be licensed under the GNU Free Documentation License version 1.3 or later.
